# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41e8e5db1eb65a4dbe81007d8ce47f9e7438aa21020889faa5719fd77001acfb7ee793beecd63d5d77f73d9d555ae06c6d0008d9ce20ae4ab114eef379da52e4

test:
  secret_key_base: a53c3ad386bdbd5defa19a3a9e1775897db5fd9aa63f0cb81212998569044dcbeb5d4a646e1384ae4902112579859fe73b78e8e2bd00fe72bd581da631340d22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
